spring:
  application:
    name: msvc-persons

  datasource:
    url: jdbc:postgresql://localhost:5432/db_ferreteria
    username: postgres
    password: sasa
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ferreteria
    # hibernate:
    #   ddl-auto: update

server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#management:
  #tracing:
    #sampling:
      #probability: 1.0
  # zipkin:
  #   tracing:
  #     endpoint: http://zipkin-server:9411/api/v2/spans

config:
  baseurl:
    endpoint:
      msvc-catalog: http://msvccatalog